### PR TITLE
Add Min-Bin's files

### PR DESCRIPTION
**Pull request by linminbin**

### CODE REVIEW

**Comment by haerdle** [comment]
thanks great work

**Comment by chencath** [comment]
1. Please have more notes on your codes
2. document please the methods in the class you defined
3. add readme file

**Comment by linminbin** [comment]
Currently I am still revising and debugging these codes (e.g., ACO). The reason I provided unfinished code is that I would like to share my code with the classmates and you to check my progress. I will absolutely add more description for the codes and provide readme file as everything is working!

Thank you!

**Comment by chencath** [comment]
No worries, just some reminders. 

 

More data source may be useful

https://data.gov.tw/


where you can find  <https://data.gov.tw/dataset/62203> 臺北市即時交通訊息,  <https://data.gov.tw/dataset/61522> 臺北捷運車站出入口座標…..


 

 

Have a good weekend.

 

 

Prof. Dr. Cathy Y.Chen.

Ladislaus von Bortkiewicz Chair of Statistics

School of Business and Economics
Humboldt-Universität zu Berlin
Unter den Linden 6

10099 Berlin, Germany

 

Website:   <https://hu.berlin/29692> https://hu.berlin/cchen

Cryptocurrency Index:  <http://hu.berlin/93629> hu.berlin/crix

Financial Risk Meter:  <http://hu.berlin/93629> hu.berlin/frm

Quantnet:  <http://quantlet.de/> www.quantlet.de/

Blockchain nights:  <https://hu.berlin/blockchain-nights> https://www.blockchainnights.com

Computer Museum:  <http://computermuseum.wiwi.hu-berlin.de/> hu.berlin/cm

**Comment by linminbin** [comment]
Professors, I appreciate your comments and useful information!

Wish you have a nice trip in China!

**Pull request merged**
